LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := Lens
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Lens.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
#LOCAL_OVERRIDES_PACKAGES := 
include $(BUILD_PREBUILT)